import mongoose from 'mongoose';
import { AgencyModel } from '../src/models/agency.model.js';
import { CarModel } from '../src/models/car.model.js';
import { CarReviewModel } from '../src/models/carReview.model.js';
import { UserModel } from '../src/models/user.model.js';

const uri =
  process.env.MONGODB_URI ||
  'mongodb+srv://subhamdas26e_db_user:travelos12345@travelos.t0loaad.mongodb.net/travelos_db?retryWrites=true&w=majority&appName=TRAVELOS';

async function seedCars() {
  try {
    await mongoose.connect(uri);
    console.log('Connected to MongoDB Atlas');

    const agency =
      (await AgencyModel.findOne({ status: { $in: ['APPROVED', 'ACTIVE'] } })) ||
      (await AgencyModel.findOne({}));
    if (!agency) {
      console.error('No agency found to assign cars. Please ensure at least one agency exists.');
      return;
    }

    console.log(`Assigning sample cars to Agency: ${agency.name || (agency as any).agencyDisplayName || agency._id}`);

    // Clear existing cars to avoid duplicates
    await CarModel.deleteMany({ agencyId: agency._id });
    console.log('Cleared existing test cars for agency');

    const sampleCars = [
      {
        agencyId: agency._id,
        name: 'Toyota Innova Crysta',
        brand: 'Toyota',
        type: 'suv',
        category: 'outstation',
        city: 'Guwahati',
        dailyPrice: 3500,
        depositPercentage: 15,
        fixedDepositAmount: 500,
        specs: {
          seats: 7,
          doors: 5,
          luggageBags: 4,
          fuel: 'Diesel',
          transmission: 'Automatic',
          hasAC: true,
          driverIncluded: true,
          modelYear: 2024,
          mileage: '14 km/l',
        },
        driver: {
          name: 'Rohit Sharma',
          photo: '/src/assets/images/cars/driver_rohit.png',
          phone: '+91 98765 43210',
          experienceYears: 5,
          rating: 4.9,
          tripsCount: 320,
          languages: ['Hindi', 'English', 'Assamese'],
          isVerified: true,
        },
        images: [
          '/src/assets/images/cars/car_innova_crysta.jpg',
          '/src/assets/images/cars/innova_view_2.png',
          '/src/assets/images/cars/innova_view_3.png',
          '/src/assets/images/cars/innova_view_4.png',
          '/src/assets/images/cars/innova_view_5.png',
        ],
        thumbnail: '/src/assets/images/cars/car_innova_crysta.jpg',
        features: [
          'Push Button Start',
          'Rear AC Vents',
          'Bluetooth Infotainment',
          'Cruise Control',
          'First Aid Kit',
          'USB Fast Charging',
          'Spacious Boot',
          'ABS & Airbags',
        ],
        inclusions: [
          'Chauffeur / Driver Included',
          'Fuel Included (up to limit)',
          'Toll & State Permits Included',
          'Fastag Enabled',
          'Free Cancellation (Up to 24 hrs)',
          'GPS Tracking & Navigation',
          'First Aid Kit Onboard',
          'Mineral Water & Sanitizers',
        ],
        exclusions: [
          'Parking Charges (actuals at venue)',
          'Extra KM Charges (beyond daily limit)',
          'Food & Accommodation (for multi-day journeys)',
          'Personal Expenses & Tips',
        ],
        cancellationPolicy: 'Free cancellation up to 24 hours before pickup time. 50% refund afterwards.',
        averageRating: 4.9,
        reviewsCount: 14,
        isAvailable: true,
        isActive: true,
        isFeatured: true,
        description:
          'The benchmark of comfort and reliability for outstation journeys, mountain roads, and family road trips. Spaciously accommodates 7 passengers with generous boot space and smooth automatic cruising.',
      },
      {
        agencyId: agency._id,
        name: 'BMW 7 Series Luxury Edition',
        brand: 'BMW',
        type: 'luxury',
        category: 'luxury',
        city: 'New Delhi',
        dailyPrice: 8500,
        depositPercentage: 20,
        fixedDepositAmount: 1500,
        specs: {
          seats: 5,
          doors: 4,
          luggageBags: 3,
          fuel: 'Petrol',
          transmission: 'Automatic',
          hasAC: true,
          driverIncluded: true,
          modelYear: 2024,
          mileage: '11 km/l',
        },
        driver: {
          name: 'Vikramjit Singh',
          photo: '/src/assets/images/cars/driver_rohit.png',
          phone: '+91 98111 22334',
          experienceYears: 8,
          rating: 4.9,
          tripsCount: 450,
          languages: ['Hindi', 'English', 'Punjabi'],
          isVerified: true,
        },
        images: ['/src/assets/images/cars/car_bmw_luxury.jpg'],
        thumbnail: '/src/assets/images/cars/car_bmw_luxury.jpg',
        features: [
          'Executive Rear Lounge',
          'Bowers & Wilkins Audio',
          'Panoramic Sky Lounge Sunroof',
          'Ambient Mood Lighting',
          'Uniformed Chauffeur',
          'Dual Zone Climate',
        ],
        inclusions: [
          'Professional Chauffeur in Uniform',
          'Unlimited Bottled Mineral Water',
          'Toll & State Border Taxes',
          'Vehicle Sanitization',
          'VIP Airport Meet & Greet',
        ],
        exclusions: ['Gratuities & Chauffeur Tips', 'Extra KM beyond package'],
        cancellationPolicy: 'Free cancellation up to 48 hours before departure. Strict VIP booking schedule.',
        averageRating: 4.9,
        reviewsCount: 8,
        isAvailable: true,
        isActive: true,
        isFeatured: true,
        description:
          'Ultra-luxurious flagship sedan for VIP delegations, high-profile business meetings, and destination weddings. Complete with uniformed chauffeur and executive amenities.',
      },
      {
        agencyId: agency._id,
        name: 'Force Tempo Traveller 12-Seater',
        brand: 'Force Motors',
        type: 'tempo_traveller',
        category: 'outstation',
        city: 'Guwahati',
        dailyPrice: 4800,
        depositPercentage: 15,
        fixedDepositAmount: 800,
        specs: {
          seats: 12,
          doors: 3,
          luggageBags: 10,
          fuel: 'Diesel',
          transmission: 'Manual',
          hasAC: true,
          driverIncluded: true,
          modelYear: 2023,
          mileage: '10 km/l',
        },
        driver: {
          name: 'Manoj Kalita',
          photo: '/src/assets/images/cars/driver_rohit.png',
          phone: '+91 97970 88990',
          experienceYears: 10,
          rating: 4.8,
          tripsCount: 560,
          languages: ['Hindi', 'Assamese', 'Bengali'],
          isVerified: true,
        },
        images: ['/src/assets/images/cars/car_tempo_traveller.jpg'],
        thumbnail: '/src/assets/images/cars/car_tempo_traveller.jpg',
        features: [
          'High Roof Standing Height',
          'Reclining Pushback Seats',
          'Overhead Luggage Carrier',
          'Mic & Infotainment System',
          'Curtains & Device Charging',
        ],
        inclusions: [
          'Experienced Mountain Route Driver',
          'Fuel & Standard Tolls',
          'Interstate Tourist Permits',
          'First Aid & Emergency Tool Kit',
        ],
        exclusions: ['Special Restricted Area Permits', 'Night Halt Allowance (after 10 PM)'],
        cancellationPolicy: 'Free cancellation up to 3 days before travel date.',
        averageRating: 4.8,
        reviewsCount: 22,
        isAvailable: true,
        isActive: true,
        isFeatured: false,
        description:
          'Ideal for joint families, pilgrim tours, and group travel to Shillong, Kaziranga, and Tawang. Ample legroom with pushback seats.',
      },
      {
        agencyId: agency._id,
        name: 'Mahindra Thar 4x4 Expedition',
        brand: 'Mahindra',
        type: 'suv',
        category: 'outstation',
        city: 'Guwahati',
        dailyPrice: 4200,
        depositPercentage: 15,
        fixedDepositAmount: 500,
        specs: {
          seats: 4,
          doors: 3,
          luggageBags: 2,
          fuel: 'Diesel',
          transmission: 'Automatic',
          hasAC: true,
          driverIncluded: true,
          modelYear: 2024,
          mileage: '12 km/l',
        },
        driver: {
          name: 'Tenzing Norbu',
          photo: '/src/assets/images/cars/driver_rohit.png',
          phone: '+91 98450 12345',
          experienceYears: 7,
          rating: 4.9,
          tripsCount: 280,
          languages: ['Hindi', 'English', 'Tibetan'],
          isVerified: true,
        },
        images: ['/src/assets/images/cars/car_mahindra_thar.jpg'],
        thumbnail: '/src/assets/images/cars/car_mahindra_thar.jpg',
        features: [
          'Mechanical Shift 4WD',
          'All-Terrain Offroad Tires',
          'Apple CarPlay & Android Auto',
          'Roll Cage Structural Protection',
          'Towing Hook & Winch',
        ],
        inclusions: ['Certified Mountain Chauffeur', 'Full Fuel Tank at Pickup', 'Basic Emergency Recovery Gear'],
        exclusions: ['Severe Terrain Recovery Charges', 'National Park Entry Fees'],
        cancellationPolicy: 'Free cancellation 48 hours prior.',
        averageRating: 4.9,
        reviewsCount: 19,
        isAvailable: true,
        isActive: true,
        isFeatured: true,
        description:
          'Conquer rugged off-road terrains, riverbeds, and high mountain passes in Arunachal and Meghalaya with complete confidence.',
      },
      {
        agencyId: agency._id,
        name: 'Hyundai i20 Asta',
        brand: 'Hyundai',
        type: 'hatchback',
        category: 'local',
        city: 'Guwahati',
        dailyPrice: 1800,
        depositPercentage: 15,
        fixedDepositAmount: 300,
        specs: {
          seats: 5,
          doors: 5,
          luggageBags: 2,
          fuel: 'Petrol',
          transmission: 'Manual',
          hasAC: true,
          driverIncluded: true,
          modelYear: 2023,
          mileage: '19 km/l',
        },
        driver: {
          name: 'Rupam Saikia',
          photo: '/src/assets/images/cars/driver_rohit.png',
          phone: '+91 99540 11223',
          experienceYears: 4,
          rating: 4.7,
          tripsCount: 190,
          languages: ['Hindi', 'Assamese'],
          isVerified: true,
        },
        images: ['/src/assets/images/cars/car_hyundai_i20.jpg'],
        thumbnail: '/src/assets/images/cars/car_hyundai_i20.jpg',
        features: [
          'Cabin Air Purifier',
          'Rear Parking Camera',
          'Electric Sunroof',
          'Wireless Device Charging',
          'Compact City Navigation',
        ],
        inclusions: ['Local City Chauffeur', 'Fuel up to 150 km / day', 'City Toll & Fastag'],
        exclusions: ['Night Halt (past 11 PM)', 'Outstation Travel (beyond state limits)'],
        cancellationPolicy: 'Free cancellation up to 12 hours before pickup.',
        averageRating: 4.7,
        reviewsCount: 12,
        isAvailable: true,
        isActive: true,
        isFeatured: false,
        description:
          'Smart, fuel-efficient, and easy to park hatchback for city commutes, shopping tours, and local transit in Guwahati.',
      },
      {
        agencyId: agency._id,
        name: 'Mercedes-Benz Tourist Mini Bus',
        brand: 'Mercedes-Benz',
        type: 'mini_bus',
        category: 'outstation',
        city: 'Guwahati',
        dailyPrice: 9200,
        depositPercentage: 15,
        fixedDepositAmount: 1500,
        specs: {
          seats: 22,
          doors: 3,
          luggageBags: 18,
          fuel: 'Diesel',
          transmission: 'Manual',
          hasAC: true,
          driverIncluded: true,
          modelYear: 2024,
          mileage: '8 km/l',
        },
        driver: {
          name: 'Deepak Bora',
          photo: '/src/assets/images/cars/driver_rohit.png',
          phone: '+91 98640 99887',
          experienceYears: 12,
          rating: 4.9,
          tripsCount: 610,
          languages: ['Hindi', 'English', 'Assamese'],
          isVerified: true,
        },
        images: ['/src/assets/images/cars/car_mercedes_minibus.jpg'],
        thumbnail: '/src/assets/images/cars/car_mercedes_minibus.jpg',
        features: [
          'Air Suspension Soft Ride',
          'PA Address Microphone',
          'High Definition TV with HDMI',
          'Spacious Center Aisle',
          'Large Underbelly Luggage Space',
        ],
        inclusions: [
          'Dual Drivers for Long Hauls',
          'All State Transit Permits',
          'Full AC Operation in Plains & Hills',
          'Emergency Tool Kit & Fire Extinguisher',
        ],
        exclusions: ['Toll & Parking (pay actuals or add on)', 'Driver Food Allowance'],
        cancellationPolicy: 'Free cancellation up to 5 days before journey date.',
        averageRating: 4.9,
        reviewsCount: 7,
        isAvailable: true,
        isActive: true,
        isFeatured: false,
        description:
          'High-capacity luxury mini coach designed for corporate retreats, wedding entourages, and large tourist groups across the North East.',
      },
      {
        agencyId: agency._id,
        name: 'Maruti Suzuki Dzire Airport Express',
        brand: 'Maruti Suzuki',
        type: 'sedan',
        category: 'airport',
        city: 'Guwahati',
        dailyPrice: 1400,
        depositPercentage: 10,
        fixedDepositAmount: 300,
        specs: {
          seats: 5,
          doors: 4,
          luggageBags: 3,
          fuel: 'CNG',
          transmission: 'Manual',
          hasAC: true,
          driverIncluded: true,
          modelYear: 2024,
          mileage: '24 km/kg',
        },
        driver: {
          name: 'Pranab Medhi',
          photo: '/src/assets/images/cars/driver_rohit.png',
          phone: '+91 98540 77112',
          experienceYears: 6,
          rating: 4.8,
          tripsCount: 420,
          languages: ['Hindi', 'Assamese', 'English'],
          isVerified: true,
        },
        images: ['/src/assets/images/cars/cat_sedan.png'],
        thumbnail: '/src/assets/images/cars/cat_sedan.png',
        features: [
          'Direct Terminal Pickup',
          'Flight Tracking Integration',
          'Clean Sanitized Cabin',
          'Luggage Loading Assistance',
          'Fastag Tolls Pre-Enabled',
        ],
        inclusions: [
          'Chauffeur with Name Placard at Airport',
          'Up to 60 Minutes Free Waiting for Delayed Flights',
          'Airport Toll & Parking Included',
          'Air Conditioned Clean Ride',
        ],
        exclusions: ['Extra Waiting beyond 60 minutes', 'Extra stops not in booked route'],
        cancellationPolicy: 'Free cancellation up to 2 hours before scheduled flight landing.',
        averageRating: 4.8,
        reviewsCount: 31,
        isAvailable: true,
        isActive: true,
        isFeatured: true,
        description:
          'Dedicated airport transfer vehicle with on-time guarantee and flight tracking. Driver receives you directly at the arrival gate with luggage assistance.',
      },
      {
        agencyId: agency._id,
        name: 'Honda City VTEC Hourly Cruiser',
        brand: 'Honda',
        type: 'sedan',
        category: 'hourly',
        city: 'Guwahati',
        dailyPrice: 2200,
        depositPercentage: 15,
        fixedDepositAmount: 500,
        specs: {
          seats: 5,
          doors: 4,
          luggageBags: 3,
          fuel: 'Petrol',
          transmission: 'Automatic',
          hasAC: true,
          driverIncluded: true,
          modelYear: 2023,
          mileage: '16 km/l',
        },
        driver: {
          name: 'Sanjeev Baruah',
          photo: '/src/assets/images/cars/driver_rohit.png',
          phone: '+91 97060 33445',
          experienceYears: 7,
          rating: 4.9,
          tripsCount: 290,
          languages: ['Hindi', 'English', 'Assamese'],
          isVerified: true,
        },
        images: ['/src/assets/images/cars/cat_sedan.png'],
        thumbnail: '/src/assets/images/cars/cat_sedan.png',
        features: [
          'Hourly Flexible Booking',
          'Leather Upholstered Seats',
          'Rear AC Blower',
          'Phone Charging Cables Provided',
          'Smooth CVT Automatic',
        ],
        inclusions: [
          'Chauffeur at Your Disposal',
          'Multiple Stops within City Limits',
          'Fuel for Included Hours',
          'AC Always On',
        ],
        exclusions: ['Inter-city Highway Tolls', 'Night Shift Charges after 10 PM'],
        cancellationPolicy: 'Free cancellation up to 6 hours before start time.',
        averageRating: 4.9,
        reviewsCount: 16,
        isAvailable: true,
        isActive: true,
        isFeatured: true,
        description:
          'Flexible hourly car hire for business meetings, doctor visits, city shopping, or sightseeing. Keep the car and driver with you as long as you need.',
      },
      {
        agencyId: agency._id,
        name: 'Mahindra Thar Self-Drive Edition',
        brand: 'Mahindra',
        type: 'suv',
        category: 'self_drive',
        city: 'Guwahati',
        dailyPrice: 3800,
        depositPercentage: 20,
        fixedDepositAmount: 2000,
        specs: {
          seats: 4,
          doors: 3,
          luggageBags: 2,
          fuel: 'Diesel',
          transmission: 'Manual',
          hasAC: true,
          driverIncluded: false,
          modelYear: 2024,
          mileage: '13 km/l',
        },
        driver: {
          name: 'Self-Drive (You Drive)',
          photo: '',
          phone: '',
          experienceYears: 0,
          rating: 5.0,
          tripsCount: 120,
          languages: ['Valid Driving License Required'],
          isVerified: true,
        },
        images: ['/src/assets/images/cars/car_mahindra_thar.jpg'],
        thumbnail: '/src/assets/images/cars/car_mahindra_thar.jpg',
        features: [
          'Self-Drive Freedom (No Chauffeur)',
          '4x4 Low Range Gearbox',
          'Comprehensive Insurance Included',
          'Fastag Auto-Debited',
          '24/7 Roadside Assistance',
        ],
        inclusions: [
          'Unlimited KM on Multi-Day Bookings',
          'Zero Dep Insurance Shield',
          'Doorstep Car Delivery Available',
          'Spare Tire and Jack Kit Included',
        ],
        exclusions: [
          'Fuel (Return with Same Level)',
          'Tolls, Fastag & State Entry Fees',
          'Security Deposit (Refunded within 24 hours of return)',
        ],
        cancellationPolicy: 'Free cancellation up to 24 hours before vehicle handover.',
        averageRating: 4.9,
        reviewsCount: 27,
        isAvailable: true,
        isActive: true,
        isFeatured: true,
        description:
          'Experience the raw thrill of driving through the North East on your own terms. Full 4x4 capability, sanitized and delivered directly to your location with zero hassle.',
      },
      {
        agencyId: agency._id,
        name: 'Toyota Fortuner Legender 4x4',
        brand: 'Toyota',
        type: 'suv',
        category: 'luxury',
        city: 'Guwahati',
        dailyPrice: 6500,
        depositPercentage: 20,
        fixedDepositAmount: 1000,
        specs: {
          seats: 7,
          doors: 5,
          luggageBags: 5,
          fuel: 'Diesel',
          transmission: 'Automatic',
          hasAC: true,
          driverIncluded: true,
          modelYear: 2024,
          mileage: '11 km/l',
        },
        driver: {
          name: 'Kalyan Gogoi',
          photo: '/src/assets/images/cars/driver_rohit.png',
          phone: '+91 94350 88221',
          experienceYears: 9,
          rating: 4.9,
          tripsCount: 380,
          languages: ['Hindi', 'English', 'Assamese'],
          isVerified: true,
        },
        images: ['/src/assets/images/cars/cat_suv.png'],
        thumbnail: '/src/assets/images/cars/cat_suv.png',
        features: [
          '4x4 Terrain Management',
          'Dual Tone Luxury Interior',
          'JBL 11-Speaker Audio System',
          'Ventilated Front & Rear Seats',
          'Powered Tailgate',
          '7 Airbags & Vehicle Stability',
        ],
        inclusions: [
          'Senior Chauffeur in Professional Attire',
          'Interstate Fastag & Permits Covered',
          'Chilled Bottled Water & Wet Wipes',
          'VIP Ground Coordination',
        ],
        exclusions: ['Parking at Venues & Hotels', 'Overnight Driver Halt beyond 10 PM'],
        cancellationPolicy: 'Free cancellation up to 48 hours before journey.',
        averageRating: 4.9,
        reviewsCount: 15,
        isAvailable: true,
        isActive: true,
        isFeatured: true,
        description:
          'Commanding road presence, unrivaled safety, and immense capability for luxury family expeditions, dignitary visits, and weddings.',
      },
    ];

    const insertedCars = await CarModel.insertMany(sampleCars);
    console.log(`Successfully seeded ${insertedCars.length} cars into MongoDB Atlas!`);

    // Add verified reviews for the cars
    const sampleUser =
      (await UserModel.findOne({})) || ({ _id: new mongoose.Types.ObjectId(), name: 'Ananya Deka' } as any);

    // Reviews for first 3 cars
    await CarReviewModel.deleteMany({ carId: { $in: insertedCars.map((c) => c._id) } });

    await CarReviewModel.create([
      {
        carId: insertedCars[0]._id, // Innova Crysta
        bookingId: new mongoose.Types.ObjectId(),
        customerId: sampleUser._id,
        customerName: 'Ananya Deka',
        customerAvatar: '/src/assets/images/cars/reviewer_ananya.png',
        rating: 5,
        comment:
          'Very comfortable ride! Rohit was very professional, courteous, and drove smoothly through the mountain roads. Car was clean and spotless. Highly recommended!',
        photos: ['/src/assets/images/cars/innova_view_2.png', '/src/assets/images/cars/innova_view_3.png'],
      },
      {
        carId: insertedCars[0]._id,
        bookingId: new mongoose.Types.ObjectId(),
        customerId: sampleUser._id,
        customerName: 'Pritam Sengupta',
        customerAvatar: '',
        rating: 5,
        comment: 'Booked for a family trip to Shillong. The Innova handled all curves with zero discomfort. Great service!',
      },
      {
        carId: insertedCars[1]._id, // BMW
        bookingId: new mongoose.Types.ObjectId(),
        customerId: sampleUser._id,
        customerName: 'Rajiv Mehra',
        customerAvatar: '',
        rating: 5,
        comment:
          'Top tier luxury experience! Vikramjit was punctual, polite and the BMW was immaculate. Perfect for our executive client.',
      },
      {
        carId: insertedCars[6]._id, // Airport Express
        bookingId: new mongoose.Types.ObjectId(),
        customerId: sampleUser._id,
        customerName: 'Nitin Sharma',
        customerAvatar: '',
        rating: 5,
        comment:
          'Flight was delayed by 40 minutes, but driver was waiting with a placard right outside Arrival. Seamless ride into town!',
      },
      {
        carId: insertedCars[8]._id, // Self Drive Thar
        bookingId: new mongoose.Types.ObjectId(),
        customerId: sampleUser._id,
        customerName: 'Akash Paul',
        customerAvatar: '',
        rating: 5,
        comment:
          'Epic self-drive experience in Meghalaya. The Thar was in mint mechanical condition, tyres were fresh, 4x4 engaged flawlessly.',
      },
    ]);

    console.log('Sample verified reviews seeded successfully across vehicles!');

    await mongoose.disconnect();
    console.log('Done!');
  } catch (error) {
    console.error('Seeding error:', error);
    process.exit(1);
  }
}

seedCars();
