// ─── Super Admin Dashboard Service (Mock Data API Contract) ─────────────────
import {
  DashboardStats,
  RevenueMetric,
  BookingMetric,
  GrowthMetric,
  Activity,
  Transaction,
  ApprovalRequest,
  SystemHealth,
  QuickAction,
} from '../types/dashboard';

export const mockDashboardStats: DashboardStats = {
  platformRevenue: {
    id: 'kpi-revenue',
    title: 'Platform Revenue',
    value: '₹48,75,230',
    growth: '12.5%',
    isPositive: true,
    comparisonText: 'from last 30 days',
    iconName: 'revenue',
    bgGradient: 'from-purple-500/10 to-indigo-500/10',
    iconColor: 'text-[#6356E5]',
  },
  gmv: {
    id: 'kpi-gmv',
    title: 'GMV',
    value: '₹3,24,75,890',
    growth: '18.3%',
    isPositive: true,
    comparisonText: 'from last 30 days',
    iconName: 'gmv',
    bgGradient: 'from-blue-500/10 to-cyan-500/10',
    iconColor: 'text-blue-600',
  },
  activeAgencies: {
    id: 'kpi-agencies',
    title: 'Active Agencies',
    value: '1,248',
    growth: '8.7%',
    isPositive: true,
    comparisonText: 'from last 30 days',
    iconName: 'agency',
    bgGradient: 'from-emerald-500/10 to-teal-500/10',
    iconColor: 'text-emerald-600',
  },
  totalUsers: {
    id: 'kpi-users',
    title: 'Total Users',
    value: '2,45,780',
    growth: '14.2%',
    isPositive: true,
    comparisonText: 'from last 30 days',
    iconName: 'users',
    bgGradient: 'from-orange-500/10 to-amber-500/10',
    iconColor: 'text-orange-500',
  },
  todaysBookings: {
    id: 'kpi-bookings',
    title: "Today's Bookings",
    value: '1,487',
    growth: '9.6%',
    isPositive: true,
    comparisonText: 'from yesterday',
    iconName: 'bookings',
    bgGradient: 'from-purple-500/10 to-pink-500/10',
    iconColor: 'text-purple-600',
  },
  runningTrips: {
    id: 'kpi-trips',
    title: 'Running Trips',
    value: '354',
    growth: '5.4%',
    isPositive: true,
    comparisonText: 'from yesterday',
    iconName: 'trips',
    bgGradient: 'from-sky-500/10 to-blue-500/10',
    iconColor: 'text-sky-500',
  },
  pendingApprovals: {
    id: 'kpi-approvals',
    title: 'Pending Approvals',
    value: '23',
    growth: '4.1%',
    isPositive: false,
    comparisonText: 'from yesterday',
    iconName: 'approvals',
    bgGradient: 'from-amber-500/10 to-yellow-500/10',
    iconColor: 'text-amber-500',
  },
  openSupportTickets: {
    id: 'kpi-tickets',
    title: 'Open Support Tickets',
    value: '18',
    growth: '10.0%',
    isPositive: false,
    comparisonText: 'from yesterday',
    iconName: 'tickets',
    bgGradient: 'from-rose-500/10 to-red-500/10',
    iconColor: 'text-rose-500',
  },
};

export const mockRevenueOverview: RevenueMetric = {
  title: 'Revenue Overview',
  currentValue: '₹48,75,230',
  growthPct: '12.5%',
  dataPoints: [
    { label: 'May 21', value: 40 },
    { label: 'May 24', value: 42 },
    { label: 'May 28', value: 38 },
    { label: 'Jun 01', value: 45 },
    { label: 'Jun 04', value: 39 },
    { label: 'Jun 08', value: 47 },
    { label: 'Jun 11', value: 50 },
    { label: 'Jun 15', value: 54 },
    { label: 'Jun 18', value: 58 },
  ],
  footerText: 'Total Revenue this month',
};

export const mockBookingTrend: BookingMetric = {
  title: 'Bookings Trend',
  currentValue: '28,745',
  growthPct: '15.3%',
  dataPoints: [
    { label: 'May 21', value: 2.2 },
    { label: 'May 24', value: 2.4 },
    { label: 'May 28', value: 3.1 },
    { label: 'Jun 01', value: 2.7 },
    { label: 'Jun 04', value: 2.9 },
    { label: 'Jun 08', value: 3.3 },
    { label: 'Jun 11', value: 3.0 },
    { label: 'Jun 15', value: 3.8 },
    { label: 'Jun 18', value: 4.2 },
  ],
  footerText: 'Total Bookings this month',
};

export const mockUserGrowth: GrowthMetric = {
  title: 'User Growth',
  currentValue: '2,45,780',
  growthPct: '14.2%',
  dataPoints: [
    { label: 'May 21', value: 14 },
    { label: 'May 24', value: 14.5 },
    { label: 'May 28', value: 18 },
    { label: 'Jun 01', value: 15.5 },
    { label: 'Jun 04', value: 17 },
    { label: 'Jun 08', value: 16 },
    { label: 'Jun 11', value: 20 },
    { label: 'Jun 15', value: 21 },
    { label: 'Jun 18', value: 24 },
  ],
  footerText: 'Total Users this month',
};

export const mockAgencyGrowth: GrowthMetric = {
  title: 'Agency Growth',
  currentValue: '1,248',
  growthPct: '8.7%',
  dataPoints: [
    { label: 'May 21', value: 700 },
    { label: 'May 24', value: 820 },
    { label: 'May 28', value: 1000 },
    { label: 'Jun 01', value: 910 },
    { label: 'Jun 04', value: 950 },
    { label: 'Jun 08', value: 1100 },
    { label: 'Jun 11', value: 1050 },
    { label: 'Jun 15', value: 1180 },
    { label: 'Jun 18', value: 1248 },
  ],
  footerText: 'Active Agencies this month',
};

export const mockRecentActivities: Activity[] = [
  {
    id: 'act-1',
    title: 'New agency "Wanderlust Holidays" registered',
    subtitle: 'Agency Registration',
    timestamp: '2 mins ago',
    type: 'agency',
    iconColor: 'text-emerald-600',
    bgColor: 'bg-emerald-50 border-emerald-100',
  },
  {
    id: 'act-2',
    title: 'User Aman Sharma completed a booking',
    subtitle: 'Booking #BK-98451',
    timestamp: '5 mins ago',
    type: 'booking',
    iconColor: 'text-blue-600',
    bgColor: 'bg-blue-50 border-blue-100',
  },
  {
    id: 'act-3',
    title: 'Booking #BK-98450 confirmed by agency',
    subtitle: 'Goa Beach Escape',
    timestamp: '12 mins ago',
    type: 'confirmation',
    iconColor: 'text-purple-600',
    bgColor: 'bg-purple-50 border-purple-100',
  },
  {
    id: 'act-4',
    title: 'New review submitted for "Himalayan Adventure"',
    subtitle: 'Review',
    timestamp: '18 mins ago',
    type: 'review',
    iconColor: 'text-amber-500',
    bgColor: 'bg-amber-50 border-amber-100',
  },
  {
    id: 'act-5',
    title: 'Payment of ₹24,999 received',
    subtitle: 'Payment #PY-88921',
    timestamp: '25 mins ago',
    type: 'payment',
    iconColor: 'text-rose-500',
    bgColor: 'bg-rose-50 border-rose-100',
  },
];

export const mockLatestTransactions: Transaction[] = [
  {
    id: 'tx-1',
    transactionId: 'PY-88921',
    agencyName: 'Wanderlust Holidays',
    amount: '₹24,999',
    status: 'Success',
    statusColor: 'emerald',
    date: 'Today, 02:45 PM',
  },
  {
    id: 'tx-2',
    transactionId: 'PY-88920',
    agencyName: 'Himalayan Treks',
    amount: '₹18,499',
    status: 'Success',
    statusColor: 'emerald',
    date: 'Today, 02:10 PM',
  },
  {
    id: 'tx-3',
    transactionId: 'PY-88919',
    agencyName: 'Goa Getaways',
    amount: '₹31,999',
    status: 'Success',
    statusColor: 'emerald',
    date: 'Today, 01:30 PM',
  },
  {
    id: 'tx-4',
    transactionId: 'PY-88918',
    agencyName: 'Travel Xperts',
    amount: '₹15,799',
    status: 'Pending',
    statusColor: 'amber',
    date: 'Today, 12:50 PM',
  },
  {
    id: 'tx-5',
    transactionId: 'PY-88917',
    agencyName: 'Explore NorthEast',
    amount: '₹12,499',
    status: 'Failed',
    statusColor: 'rose',
    date: 'Today, 11:15 AM',
  },
];

export const mockPendingApprovals: ApprovalRequest[] = [
  {
    id: 'app-1',
    name: 'Mountain World Treks',
    type: 'Agency Registration',
    timeAgo: '2 hours ago',
    status: 'Pending',
    iconType: 'building',
  },
  {
    id: 'app-2',
    name: 'Adventure Packages India',
    type: 'Package Submission',
    timeAgo: '3 hours ago',
    status: 'Pending',
    iconType: 'package',
  },
  {
    id: 'app-3',
    name: 'Holiday Hub Agency',
    type: 'Agency Registration',
    timeAgo: '5 hours ago',
    status: 'Pending',
    iconType: 'building',
  },
  {
    id: 'app-4',
    name: 'Kerala Backwaters Tour',
    type: 'Package Submission',
    timeAgo: '6 hours ago',
    status: 'Pending',
    iconType: 'package',
  },
];

export const mockSystemHealth: SystemHealth = {
  overallStatus: 'All Systems Operational',
  services: [
    {
      id: 'srv-1',
      name: 'API Services',
      status: 'Operational',
      uptimePct: '99.99%',
      iconType: 'api',
    },
    {
      id: 'srv-2',
      name: 'Database',
      status: 'Operational',
      uptimePct: '99.98%',
      iconType: 'db',
    },
    {
      id: 'srv-3',
      name: 'Payment Gateway',
      status: 'Operational',
      uptimePct: '100%',
      iconType: 'gateway',
    },
    {
      id: 'srv-4',
      name: 'Storage',
      status: 'Operational',
      uptimePct: '99.95%',
      iconType: 'storage',
    },
  ],
};

export const mockQuickActions: QuickAction[] = [
  {
    id: 'qa-1',
    title: 'Add New Agency',
    subtitle: 'Register new agency',
    iconName: 'add_agency',
    color: 'purple',
    actionKey: 'add_agency',
  },
  {
    id: 'qa-2',
    title: 'Create Announcement',
    subtitle: 'Send to all users',
    iconName: 'announcement',
    color: 'blue',
    actionKey: 'create_announcement',
  },
  {
    id: 'qa-3',
    title: 'Generate Report',
    subtitle: 'Download platform report',
    iconName: 'report',
    color: 'emerald',
    actionKey: 'generate_report',
  },
  {
    id: 'qa-4',
    title: 'Manage Banners',
    subtitle: 'Update homepage banners',
    iconName: 'banner',
    color: 'orange',
    actionKey: 'manage_banners',
  },
  {
    id: 'qa-5',
    title: 'View Analytics',
    subtitle: 'Detailed analytics',
    iconName: 'analytics',
    color: 'indigo',
    actionKey: 'view_analytics',
  },
];

export const adminDashboardService = {
  getStats: async (): Promise<DashboardStats> => mockDashboardStats,
  getRevenueOverview: async (): Promise<RevenueMetric> => mockRevenueOverview,
  getBookingTrend: async (): Promise<BookingMetric> => mockBookingTrend,
  getUserGrowth: async (): Promise<GrowthMetric> => mockUserGrowth,
  getAgencyGrowth: async (): Promise<GrowthMetric> => mockAgencyGrowth,
  getRecentActivities: async (): Promise<Activity[]> => mockRecentActivities,
  getLatestTransactions: async (): Promise<Transaction[]> => mockLatestTransactions,
  getPendingApprovals: async (): Promise<ApprovalRequest[]> => mockPendingApprovals,
  getSystemHealth: async (): Promise<SystemHealth> => mockSystemHealth,
  getQuickActions: async (): Promise<QuickAction[]> => mockQuickActions,
};
