import {
  AgencyRequestItem,
  AgencyRequestSummaryStats,
  AgencyRequestFilters,
} from '../types/agencyRequest';

export const mockAgencyRequestStats: AgencyRequestSummaryStats = {
  pendingRequests: { count: 34, growth: '21.4%', isPositive: true },
  approvedToday: { count: 12, growth: '33.3%', isPositive: true },
  rejectedToday: { count: 3, growth: '25%', isPositive: false },
  underReview: { count: 8, growth: '14.3%', isPositive: true },
  documentsMissing: { count: 7, growth: '16.7%', isPositive: true },
  avgApprovalTime: { value: '2h 45m', growth: '8.3%', isPositive: true },
};

export const mockAgencyRequestsList: AgencyRequestItem[] = [
  {
    id: 'REQ-101',
    applicationId: 'APP-2024-00567',
    agencyName: 'Wanderlust Holidays',
    logo: 'https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=200&auto=format&fit=crop',
    ownerName: 'Aman Sharma',
    ownerEmail: 'aman@wanderlust.com',
    ownerPhone: '+91 98765 43210',
    businessType: 'Tour Operator',
    submittedDate: 'May 21, 2024 10:30 AM',
    gstNumber: '27AABCU9603R1ZV',
    website: 'www.wanderlustholidays.com',
    establishedYear: '2018',
    officeAddress: '123, Andheri West, Mumbai, Maharashtra - 400058',
    aadhaarNumber: 'XXXX XXXX 1234',
    panNumber: 'ABCDE1234F',
    city: 'Mumbai',
    state: 'Maharashtra',
    documentsUploadedCount: 6,
    documentsTotalCount: 6,
    verificationStatus: 'Complete',
    reviewStatus: 'Pending',
    complianceScore: 92,
    verificationChecklist: [
      { id: 'vc1', label: 'GST Verification', status: 'Verified' },
      { id: 'vc2', label: 'PAN Verification', status: 'Verified' },
      { id: 'vc3', label: 'Business License', status: 'Verified' },
      { id: 'vc4', label: 'Bank Verification', status: 'Under Review' },
      { id: 'vc5', label: 'KYC Verification', status: 'Verified' },
      { id: 'vc6', label: 'Office Address', status: 'Pending' },
    ],
    documents: [
      { id: 'd1', name: 'GST Certificate.pdf', type: 'GST', status: 'Approved', fileUrl: '#', uploadedAt: 'May 21, 2024 10:32 AM' },
      { id: 'd2', name: 'PAN Card Copy.pdf', type: 'PAN', status: 'Approved', fileUrl: '#', uploadedAt: 'May 21, 2024 10:35 AM' },
      { id: 'd3', name: 'Trade License.pdf', type: 'License', status: 'Approved', fileUrl: '#', uploadedAt: 'May 21, 2024 10:38 AM' },
      { id: 'd4', name: 'Bank Statement.pdf', type: 'Bank Proof', status: 'Pending', fileUrl: '#', uploadedAt: 'May 21, 2024 10:40 AM' },
      { id: 'd5', name: 'Office Premises Proof.pdf', type: 'Address', status: 'Approved', fileUrl: '#', uploadedAt: 'May 21, 2024 10:42 AM' },
      { id: 'd6', name: 'Owner Aadhaar Card.pdf', type: 'Identity', status: 'Approved', fileUrl: '#', uploadedAt: 'May 21, 2024 10:45 AM' },
    ],
    timeline: [
      { id: 't1', title: 'Application Submitted', timestamp: 'May 21, 2024 10:30 AM', completed: true },
      { id: 't2', title: 'Documents Uploaded', timestamp: 'May 21, 2024 10:45 AM', completed: true },
      { id: 't3', title: 'Verification Started', timestamp: 'May 21, 2024 11:20 AM', completed: true },
      { id: 't4', title: 'Admin Viewed', timestamp: 'May 21, 2024 12:15 PM', completed: true },
      { id: 't5', title: 'Pending Approval', timestamp: '—', completed: false },
    ],
    activities: [
      { id: 'act1', timestamp: 'May 21, 2024 12:15 PM', adminName: 'Super Admin', action: 'Viewed Application', notes: 'Checked GST & PAN validity', status: 'Under Audit' },
      { id: 'act2', timestamp: 'May 21, 2024 11:20 AM', adminName: 'System Bot', action: 'KYC Verified', notes: 'Aadhaar OTP verified', status: 'Automated Pass' },
    ],
  },
  {
    id: 'REQ-102',
    applicationId: 'APP-2024-00568',
    agencyName: 'Himalayan Treks',
    logo: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=200&auto=format&fit=crop',
    ownerName: 'Neha Rawat',
    ownerEmail: 'neha@himalayantreks.com',
    ownerPhone: '+91 98765 11122',
    businessType: 'Adventure',
    submittedDate: 'May 21, 2024 09:15 AM',
    gstNumber: '01AAACH1Z34B1ZK',
    website: 'www.himalayantreks.com',
    establishedYear: '2020',
    officeAddress: 'Mall Road, Dehradun, Uttarakhand - 248001',
    aadhaarNumber: 'XXXX XXXX 5678',
    panNumber: 'FGHIJ5678K',
    city: 'Dehradun',
    state: 'Uttarakhand',
    documentsUploadedCount: 4,
    documentsTotalCount: 6,
    verificationStatus: 'Missing Docs',
    reviewStatus: 'Pending',
    complianceScore: 68,
    verificationChecklist: [
      { id: 'vc1', label: 'GST Verification', status: 'Verified' },
      { id: 'vc2', label: 'PAN Verification', status: 'Verified' },
      { id: 'vc3', label: 'Business License', status: 'Missing' },
      { id: 'vc4', label: 'Bank Verification', status: 'Pending' },
      { id: 'vc5', label: 'KYC Verification', status: 'Verified' },
      { id: 'vc6', label: 'Office Address', status: 'Verified' },
    ],
    documents: [],
    timeline: [],
    activities: [],
  },
  {
    id: 'REQ-103',
    applicationId: 'APP-2024-00569',
    agencyName: 'Goa Getaways',
    logo: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=200&auto=format&fit=crop',
    ownerName: 'Rohit Verma',
    ownerEmail: 'info@goagetaways.com',
    ownerPhone: '+91 98765 22233',
    businessType: 'Tour Operator',
    submittedDate: 'May 20, 2024 04:45 PM',
    gstNumber: '30AABCG7890C1Z3',
    website: 'www.goagetaways.com',
    establishedYear: '2019',
    officeAddress: 'Panjim Beach Road, Goa - 403001',
    aadhaarNumber: 'XXXX XXXX 9012',
    panNumber: 'LMNOP9012Q',
    city: 'Goa',
    state: 'Goa',
    documentsUploadedCount: 6,
    documentsTotalCount: 6,
    verificationStatus: 'Complete',
    reviewStatus: 'Under Review',
    complianceScore: 88,
    verificationChecklist: [],
    documents: [],
    timeline: [],
    activities: [],
  },
  {
    id: 'REQ-104',
    applicationId: 'APP-2024-00570',
    agencyName: 'Kerala Backwaters Tours',
    logo: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?q=80&w=200&auto=format&fit=crop',
    ownerName: 'Sanjay Nair',
    ownerEmail: 'sanjay@keralabackwaters.com',
    ownerPhone: '+91 98765 33344',
    businessType: 'Tour Operator',
    submittedDate: 'May 20, 2024 02:20 PM',
    gstNumber: '32AAACK1234D1Z5',
    website: 'www.keralabackwaters.com',
    establishedYear: '2017',
    officeAddress: 'MG Road, Kochi, Kerala - 682016',
    aadhaarNumber: 'XXXX XXXX 3456',
    panNumber: 'RSTUV3456W',
    city: 'Kochi',
    state: 'Kerala',
    documentsUploadedCount: 5,
    documentsTotalCount: 6,
    verificationStatus: 'Under Review',
    reviewStatus: 'Under Review',
    complianceScore: 82,
    verificationChecklist: [],
    documents: [],
    timeline: [],
    activities: [],
  },
  {
    id: 'REQ-105',
    applicationId: 'APP-2024-00571',
    agencyName: 'Adventure India',
    logo: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=200&auto=format&fit=crop',
    ownerName: 'Vikram Singh',
    ownerEmail: 'vikram@adventureindia.com',
    ownerPhone: '+91 98765 44455',
    businessType: 'Adventure',
    submittedDate: 'May 20, 2024 11:05 AM',
    gstNumber: '07AACR4567E1Z1',
    website: 'www.adventureindia.com',
    establishedYear: '2021',
    officeAddress: 'Old Manali, Himachal Pradesh - 175131',
    aadhaarNumber: 'XXXX XXXX 7890',
    panNumber: 'XYZAB7890C',
    city: 'Manali',
    state: 'Himachal Pradesh',
    documentsUploadedCount: 3,
    documentsTotalCount: 6,
    verificationStatus: 'Missing Docs',
    reviewStatus: 'Pending',
    complianceScore: 55,
    verificationChecklist: [],
    documents: [],
    timeline: [],
    activities: [],
  },
  {
    id: 'REQ-106',
    applicationId: 'APP-2024-00572',
    agencyName: 'Holiday Hub Agency',
    logo: 'https://images.unsplash.com/photo-1476514525535-ce74f45814ce?q=80&w=200&auto=format&fit=crop',
    ownerName: 'Priya Mehta',
    ownerEmail: 'priya@holidayhub.com',
    ownerPhone: '+91 98765 55566',
    businessType: 'Travel Agency',
    submittedDate: 'May 19, 2024 05:30 PM',
    gstNumber: '29AABCH6789F1Z2',
    website: 'www.holidayhub.com',
    establishedYear: '2019',
    officeAddress: 'Indiranagar, Bangalore, Karnataka - 560038',
    aadhaarNumber: 'XXXX XXXX 1122',
    panNumber: 'DEFGH1122I',
    city: 'Bangalore',
    state: 'Karnataka',
    documentsUploadedCount: 6,
    documentsTotalCount: 6,
    verificationStatus: 'Complete',
    reviewStatus: 'Pending',
    complianceScore: 94,
    verificationChecklist: [],
    documents: [],
    timeline: [],
    activities: [],
  },
  {
    id: 'REQ-107',
    applicationId: 'APP-2024-00573',
    agencyName: 'Explore NorthEast',
    logo: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?q=80&w=200&auto=format&fit=crop',
    ownerName: 'Tenzing Lepcha',
    ownerEmail: 'tenzing@explorenortheast.com',
    ownerPhone: '+91 98765 66677',
    businessType: 'Tour Operator',
    submittedDate: 'May 19, 2024 03:10 PM',
    gstNumber: '18AABCE3456G1Z9',
    website: 'www.explorenortheast.com',
    establishedYear: '2016',
    officeAddress: 'GS Road, Guwahati, Assam - 781005',
    aadhaarNumber: 'XXXX XXXX 3344',
    panNumber: 'JKLMN3344O',
    city: 'Guwahati',
    state: 'Assam',
    documentsUploadedCount: 4,
    documentsTotalCount: 6,
    verificationStatus: 'Under Review',
    reviewStatus: 'Pending',
    complianceScore: 78,
    verificationChecklist: [],
    documents: [],
    timeline: [],
    activities: [],
  },
  {
    id: 'REQ-108',
    applicationId: 'APP-2024-00574',
    agencyName: 'Desert Dunes Travels',
    logo: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?q=80&w=200&auto=format&fit=crop',
    ownerName: 'Mohit Choudhary',
    ownerEmail: 'mohit@desertdunes.com',
    ownerPhone: '+91 98765 77788',
    businessType: 'Tour Operator',
    submittedDate: 'May 19, 2024 11:45 AM',
    gstNumber: '08AABCD7891H1Z7',
    website: 'www.desertdunes.com',
    establishedYear: '2022',
    officeAddress: 'Fort Road, Jaisalmer, Rajasthan - 345001',
    aadhaarNumber: 'XXXX XXXX 5566',
    panNumber: 'PQRST5566U',
    city: 'Jaisalmer',
    state: 'Rajasthan',
    documentsUploadedCount: 2,
    documentsTotalCount: 6,
    verificationStatus: 'Missing Docs',
    reviewStatus: 'Pending',
    complianceScore: 45,
    verificationChecklist: [],
    documents: [],
    timeline: [],
    activities: [],
  },
  {
    id: 'REQ-109',
    applicationId: 'APP-2024-00575',
    agencyName: 'Sikkim Serenity',
    logo: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?q=80&w=200&auto=format&fit=crop',
    ownerName: 'Pema Bhutia',
    ownerEmail: 'pema@sikkimserenity.com',
    ownerPhone: '+91 98765 88899',
    businessType: 'Tour Operator',
    submittedDate: 'May 18, 2024 06:20 PM',
    gstNumber: '11AABCS1234I1Z8',
    website: 'www.sikkimserenity.com',
    establishedYear: '2020',
    officeAddress: 'MG Marg, Gangtok, Sikkim - 737101',
    aadhaarNumber: 'XXXX XXXX 7788',
    panNumber: 'VWXYZ7788A',
    city: 'Gangtok',
    state: 'Sikkim',
    documentsUploadedCount: 6,
    documentsTotalCount: 6,
    verificationStatus: 'Complete',
    reviewStatus: 'Under Review',
    complianceScore: 90,
    verificationChecklist: [],
    documents: [],
    timeline: [],
    activities: [],
  },
  {
    id: 'REQ-110',
    applicationId: 'APP-2024-00576',
    agencyName: 'Cityscape Holidays',
    logo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=200&auto=format&fit=crop',
    ownerName: 'Karan Malhotra',
    ownerEmail: 'karan@cityscapeholidays.com',
    ownerPhone: '+91 98765 99900',
    businessType: 'Travel Agency',
    submittedDate: 'May 18, 2024 02:15 PM',
    gstNumber: '24AABCC5678J1Z6',
    website: 'www.cityscapeholidays.com',
    establishedYear: '2023',
    officeAddress: 'Connaught Place, New Delhi - 110001',
    aadhaarNumber: 'XXXX XXXX 9900',
    panNumber: 'BCDEF9900G',
    city: 'Delhi',
    state: 'Delhi',
    documentsUploadedCount: 5,
    documentsTotalCount: 6,
    verificationStatus: 'Under Review',
    reviewStatus: 'Pending',
    complianceScore: 72,
    verificationChecklist: [],
    documents: [],
    timeline: [],
    activities: [],
  },
];

export const adminAgencyRequestService = {
  async getSummaryStats(): Promise<AgencyRequestSummaryStats> {
    return new Promise((resolve) => {
      setTimeout(() => resolve(mockAgencyRequestStats), 100);
    });
  },

  async getAgencyRequests(filters?: Partial<AgencyRequestFilters>): Promise<AgencyRequestItem[]> {
    return new Promise((resolve) => {
      setTimeout(() => {
        let result = [...mockAgencyRequestsList];
        if (filters?.search) {
          const q = filters.search.toLowerCase();
          result = result.filter(
            (r) =>
              r.agencyName.toLowerCase().includes(q) ||
              r.ownerName.toLowerCase().includes(q) ||
              r.ownerEmail.toLowerCase().includes(q) ||
              r.applicationId.toLowerCase().includes(q) ||
              r.gstNumber.toLowerCase().includes(q)
          );
        }
        if (filters?.status && filters.status !== 'All Status') {
          result = result.filter((r) => r.reviewStatus === filters.status);
        }
        if (filters?.businessType && filters.businessType !== 'All Types') {
          result = result.filter((r) => r.businessType === filters.businessType);
        }
        if (filters?.verificationStatus && filters.verificationStatus !== 'All Status') {
          result = result.filter((r) => r.verificationStatus === filters.verificationStatus);
        }
        resolve(result);
      }, 100);
    });
  },

  async approveRequest(id: string, notes?: string): Promise<{ success: boolean }> {
    return new Promise((resolve) => {
      setTimeout(() => resolve({ success: true }), 150);
    });
  },

  async rejectRequest(id: string, reason?: string): Promise<{ success: boolean }> {
    return new Promise((resolve) => {
      setTimeout(() => resolve({ success: true }), 150);
    });
  },

  async requestMoreDocuments(id: string, requestedDocs?: string[]): Promise<{ success: boolean }> {
    return new Promise((resolve) => {
      setTimeout(() => resolve({ success: true }), 150);
    });
  },
};
